# GPCR Mechanism Analysis - PyMOL Visualization
# Generated by ProtOS GPCR Binding Pocket Workflow
#
# Shows 8 adrenergic receptor structures with hypothesis markers

# Fetch structures
fetch 3sn6
fetch 4ldo
fetch 2y02
fetch 2y04
fetch 2y00
fetch 2rh1
fetch 3ny9
fetch 2vt4

# Basic setup
bg_color white
set ray_shadows, 0
set antialias, 2
hide everything

# Show as cartoon
show cartoon, 3sn6 and chain R
color #2ca02c, 3sn6
show cartoon, 4ldo and chain A
color #98df8a, 4ldo
show cartoon, 2y02 and chain A
color #17becf, 2y02
show cartoon, 2y04 and chain A
color #ff7f0e, 2y04
show cartoon, 2y00 and chain A
color #ffbb78, 2y00
show cartoon, 2rh1 and chain A
color #d62728, 2rh1
show cartoon, 3ny9 and chain A
color #ff9896, 3ny9
show cartoon, 2vt4 and chain A
color #9467bd, 2vt4

# Show ligands
show sticks, 3sn6 and resn P0G
color yellow, 3sn6 and resn P0G
show sticks, 4ldo and resn ALE
color yellow, 4ldo and resn ALE
show sticks, 2y02 and resn WHJ
color yellow, 2y02 and resn WHJ
show sticks, 2y04 and resn 68H
color yellow, 2y04 and resn 68H
show sticks, 2y00 and resn Y00
color yellow, 2y00 and resn Y00
show sticks, 2rh1 and resn CAU
color yellow, 2rh1 and resn CAU
show sticks, 3ny9 and resn JSZ
color yellow, 3ny9 and resn JSZ
show sticks, 2vt4 and resn P32
color yellow, 2vt4 and resn P32

# Highlight key GRN positions
# H1: S5.43 (agonist binding marker)
# H2: W6.48 (toggle switch)
# H3: N6.55 (water marker)

# 3SN6 5.43
show sticks, 3sn6 and chain R and resi 171
# 3SN6 6.48
show sticks, 3sn6 and chain R and resi 229
# 3SN6 6.55
show sticks, 3sn6 and chain R and resi 236
# 4LDO 5.43
show sticks, 4ldo and chain A and resi 346
# 4LDO 6.48
show sticks, 4ldo and chain A and resi 398
# 4LDO 6.55
show sticks, 4ldo and chain A and resi 405
# 2Y02 5.43
show sticks, 2y02 and chain A and resi 179
# 2Y02 6.48
show sticks, 2y02 and chain A and resi 231
# 2Y02 6.55
show sticks, 2y02 and chain A and resi 238
# 2Y04 5.43
show sticks, 2y04 and chain A and resi 179
# 2Y04 6.48
show sticks, 2y04 and chain A and resi 231
# 2Y04 6.55
show sticks, 2y04 and chain A and resi 238
# 2Y00 5.43
show sticks, 2y00 and chain A and resi 179
# 2Y00 6.48
show sticks, 2y00 and chain A and resi 231
# 2Y00 6.55
show sticks, 2y00 and chain A and resi 238
# 2RH1 5.43
show sticks, 2rh1 and chain A and resi 175
# 2RH1 6.48
show sticks, 2rh1 and chain A and resi 226
# 2RH1 6.55
show sticks, 2rh1 and chain A and resi 233
# 3NY9 5.43
show sticks, 3ny9 and chain A and resi 172
# 3NY9 6.48
show sticks, 3ny9 and chain A and resi 223
# 3NY9 6.55
show sticks, 3ny9 and chain A and resi 230
# 2VT4 5.43
show sticks, 2vt4 and chain A and resi 172
# 2VT4 6.48
show sticks, 2vt4 and chain A and resi 219
# 2VT4 6.55
show sticks, 2vt4 and chain A and resi 226

# Create scenes for each hypothesis

# Scene 1: Overview
orient
zoom all, 5
scene overview, store

# Scene 2: H1 - S5.43 binding
# Focus on agonist binding site
scene H1_S543, store

# Scene 3: H2 - W6.48 toggle switch
scene H2_W648, store

# Scene 4: H3 - N6.55 water
scene H3_N655, store

# Usage:
# scene overview  - show all structures
# scene H1_S543   - focus on S5.43
# scene H2_W648   - focus on W6.48
# scene H3_N655   - focus on N6.55
