# GPCR Mechanism Analysis - PyMOL Visualization
# Generated by ProtOS GPCR Binding Pocket Workflow

# Fetch structures
fetch 3sn6
fetch 4ldo
fetch 2y02
fetch 2y04
fetch 2y00
fetch 2rh1
fetch 3ny9
fetch 2vt4

# Basic setup
bg_color white
set ray_shadows, 0
hide everything

# Extract GPCR chains and show as cartoon
create 3SN6_gpcr, 3sn6 and chain R
show cartoon, 3SN6_gpcr
color forest, 3SN6_gpcr
set cartoon_transparency, 0.7, 3SN6_gpcr
create 4LDO_gpcr, 4ldo and chain A
show cartoon, 4LDO_gpcr
color lime, 4LDO_gpcr
set cartoon_transparency, 0.7, 4LDO_gpcr
create 2Y02_gpcr, 2y02 and chain A
show cartoon, 2Y02_gpcr
color cyan, 2Y02_gpcr
set cartoon_transparency, 0.7, 2Y02_gpcr
create 2Y04_gpcr, 2y04 and chain A
show cartoon, 2Y04_gpcr
color orange, 2Y04_gpcr
set cartoon_transparency, 0.7, 2Y04_gpcr
create 2Y00_gpcr, 2y00 and chain A
show cartoon, 2Y00_gpcr
color tv_orange, 2Y00_gpcr
set cartoon_transparency, 0.7, 2Y00_gpcr
create 2RH1_gpcr, 2rh1 and chain A
show cartoon, 2RH1_gpcr
color firebrick, 2RH1_gpcr
set cartoon_transparency, 0.7, 2RH1_gpcr
create 3NY9_gpcr, 3ny9 and chain A
show cartoon, 3NY9_gpcr
color salmon, 3NY9_gpcr
set cartoon_transparency, 0.7, 3NY9_gpcr
create 2VT4_gpcr, 2vt4 and chain A
show cartoon, 2VT4_gpcr
color slate, 2VT4_gpcr
set cartoon_transparency, 0.7, 2VT4_gpcr

# Show ligands
show sticks, 3SN6_gpcr and resn P0G
color green, 3SN6_gpcr and resn P0G
show sticks, 4LDO_gpcr and resn ALE
color green, 4LDO_gpcr and resn ALE
show sticks, 2Y02_gpcr and resn WHJ
color green, 2Y02_gpcr and resn WHJ
show sticks, 2Y04_gpcr and resn 68H
color green, 2Y04_gpcr and resn 68H
show sticks, 2Y00_gpcr and resn Y00
color green, 2Y00_gpcr and resn Y00
show sticks, 2RH1_gpcr and resn CAU
color red, 2RH1_gpcr and resn CAU
show sticks, 3NY9_gpcr and resn JSZ
color red, 3NY9_gpcr and resn JSZ
show sticks, 2VT4_gpcr and resn P32
color red, 2VT4_gpcr and resn P32

# Key GRN positions for hypothesis testing
# Residue numbers from ProtOS GRN annotation:
# 3SN6 5.43 = residue 203
# 4LDO 5.43 = residue 1203
# 2Y02 5.43 = residue 211
# 2Y04 5.43 = residue 211
# 2Y00 5.43 = residue 211
# 2RH1 5.43 = residue 203
# 3NY9 5.43 = residue 203
# 2VT4 5.43 = residue 211
select grn_5_43, (3SN6_gpcr and chain R and resi 203) or (4LDO_gpcr and chain A and resi 1203) or (2Y02_gpcr and chain A and resi 211) or (2Y04_gpcr and chain A and resi 211) or (2Y00_gpcr and chain A and resi 211) or (2RH1_gpcr and chain A and resi 203) or (3NY9_gpcr and chain A and resi 203) or (2VT4_gpcr and chain A and resi 211)
show sticks, grn_5_43 and sidechain
# 3SN6 6.48 = residue 286
# 4LDO 6.48 = residue 1286
# 2Y02 6.48 = residue 303
# 2Y04 6.48 = residue 303
# 2Y00 6.48 = residue 303
# 2RH1 6.48 = residue 286
# 3NY9 6.48 = residue 286
# 2VT4 6.48 = residue 303
select grn_6_48, (3SN6_gpcr and chain R and resi 286) or (4LDO_gpcr and chain A and resi 1286) or (2Y02_gpcr and chain A and resi 303) or (2Y04_gpcr and chain A and resi 303) or (2Y00_gpcr and chain A and resi 303) or (2RH1_gpcr and chain A and resi 286) or (3NY9_gpcr and chain A and resi 286) or (2VT4_gpcr and chain A and resi 303)
show sticks, grn_6_48 and sidechain
# 3SN6 6.55 = residue 293
# 4LDO 6.55 = residue 1293
# 2Y02 6.55 = residue 310
# 2Y04 6.55 = residue 310
# 2Y00 6.55 = residue 310
# 2RH1 6.55 = residue 293
# 3NY9 6.55 = residue 293
# 2VT4 6.55 = residue 310
select grn_6_55, (3SN6_gpcr and chain R and resi 293) or (4LDO_gpcr and chain A and resi 1293) or (2Y02_gpcr and chain A and resi 310) or (2Y04_gpcr and chain A and resi 310) or (2Y00_gpcr and chain A and resi 310) or (2RH1_gpcr and chain A and resi 293) or (3NY9_gpcr and chain A and resi 293) or (2VT4_gpcr and chain A and resi 310)
show sticks, grn_6_55 and sidechain

# Align all to reference (2RH1)
super 3sn6_gpcr and name CA, 2rh1_gpcr and name CA
super 4ldo_gpcr and name CA, 2rh1_gpcr and name CA
super 2y02_gpcr and name CA, 2rh1_gpcr and name CA
super 2y04_gpcr and name CA, 2rh1_gpcr and name CA
super 2y00_gpcr and name CA, 2rh1_gpcr and name CA
super 3ny9_gpcr and name CA, 2rh1_gpcr and name CA
super 2vt4_gpcr and name CA, 2rh1_gpcr and name CA

# Create scenes
orient
zoom all, 5
scene overview, store

# Color GRN positions
color magenta, grn_5_43 and sidechain
color cyan, grn_6_48 and sidechain
color yellow, grn_6_55 and sidechain

# Create groups
group agonists, 3sn6_gpcr 4ldo_gpcr 2y02_gpcr
group partial_agonists, 2y04_gpcr 2y00_gpcr
group inverse_agonists, 2rh1_gpcr 3ny9_gpcr
group antagonists, 2vt4_gpcr

# Usage:
# scene overview, recall
# enable agonists; disable inverse_agonists
