# Figure 3.1b (C1C2) — MO-GRN Functional Sets on C1C2 (3UG9)
# ===========================================================================
# Generated by mogrn_microswitches_c1c2.py from mo_ref.csv annotations.
# All 20 key MO-GRN positions, 6 functional sets, no labels.
#
# Residue mapping (MO-GRN → C1C2 residue):
#   2.46 → E121
#   2.47 → E122
#   3.42 → R159
#   3.45 → E162
#   3.46 → W163
#   3.49 → T166
#   3.50 → C167
#   3.53 → I170
#   3.56 → H173
#   4.47 → D195
#   4.51 → I199
#   4.54 → G202
#   5.44 → V214
#   5.47 → F217
#   6.50 → W262
#   6.53 → F265
#   6.54 → P266
#   7.46 → D292
#   7.49 → S295
#   7.50 → K296
#
# Usage:
#   pymol mogrn_microswitches_c1c2.pml
# ===========================================================================

# Load shared colorscales (colors + render settings)
@thesis/shared/colorscales_pymol.pml

# --- TM helix colors (spectral scheme) ---
set_color tm2_color, [0.239, 0.353, 0.502]
set_color tm3_color, [0.271, 0.482, 0.420]
set_color tm4_color, [0.416, 0.600, 0.306]
set_color tm5_color, [0.831, 0.627, 0.235]
set_color tm6_color, [0.737, 0.424, 0.145]
set_color tm7_color, [0.757, 0.400, 0.420]

# =============================================================================
# Load structure
# =============================================================================
fetch 3UG9, c1c2, type=pdb, async=0
remove solvent
remove c1c2 and not chain A

# Backbone: gray, transparent
hide everything
show cartoon, c1c2 and chain A and polymer
color backbone, c1c2
set cartoon_transparency, 0.75, c1c2

# Retinal chromophore (always visible)
select retinal, c1c2 and chain A and resn RET
show sticks, retinal
color retinal_rust, retinal
set stick_radius, 0.20, retinal

# =============================================================================
# Define ALL residue selections (by MO-GRN position)
# =============================================================================
select grn_2_46, c1c2 and chain A and resi 121
select grn_2_47, c1c2 and chain A and resi 122
select grn_3_42, c1c2 and chain A and resi 159
select grn_3_45, c1c2 and chain A and resi 162
select grn_3_46, c1c2 and chain A and resi 163
select grn_3_49, c1c2 and chain A and resi 166
select grn_3_50, c1c2 and chain A and resi 167
select grn_3_53, c1c2 and chain A and resi 170
select grn_3_56, c1c2 and chain A and resi 173
select grn_4_47, c1c2 and chain A and resi 195
select grn_4_51, c1c2 and chain A and resi 199
select grn_4_54, c1c2 and chain A and resi 202
select grn_5_44, c1c2 and chain A and resi 214
select grn_5_47, c1c2 and chain A and resi 217
select grn_6_50, c1c2 and chain A and resi 262
select grn_6_53, c1c2 and chain A and resi 265
select grn_6_54, c1c2 and chain A and resi 266
select grn_7_46, c1c2 and chain A and resi 292
select grn_7_49, c1c2 and chain A and resi 295
select grn_7_50, c1c2 and chain A and resi 296

# =============================================================================
# Define functional sets
# =============================================================================
select set1_schiff, grn_3_42 or grn_3_45 or grn_7_46 or grn_7_50
select set2_proton, grn_3_45 or grn_3_49 or grn_3_53 or grn_3_56
select set3_dcgate, grn_3_50 or grn_4_47
select set4_pocket, grn_3_46 or grn_5_44 or grn_5_47 or grn_6_50 or grn_6_53
select set5_tuning, grn_3_53 or grn_4_51 or grn_4_54 or grn_6_54 or grn_7_49
select set6_channel, grn_2_46 or grn_2_47
select all_grn, set1_schiff or set2_proton or set3_dcgate or set4_pocket or set5_tuning or set6_channel

# Start with all sticks hidden
hide sticks, all_grn
deselect

# =============================================================================
# Camera
# =============================================================================
set_view (\
    -0.963549674,   -0.143934369,   -0.225513399,\
     0.149556443,   -0.988720417,   -0.007953573,\
    -0.221825153,   -0.041390404,    0.974206805,\
     0.000002506,    0.000059575, -263.628967285,\
     7.338849068,   34.503849030,   13.155744553,\
   208.342391968,  318.911865234,   20.000000000 )

# =============================================================================
# SET1_SCHIFF — Schiff base & counterions (R159, E162, D292, K296)
# =============================================================================
color backbone, all_grn
show sticks, set1_schiff
color tm3_color, grn_3_42 or grn_3_45
color tm7_color, grn_7_46 or grn_7_50
set stick_radius, 0.15, set1_schiff
distance d_345_750, (resi 162 and name OE1+OE2+OD1+OD2), (resi 296 and name NZ), cutoff=5
set dash_color, dark_gray, d_345_750
set dash_gap, 0.25, d_345_750
set dash_width, 1.5, d_345_750
hide labels, d_345_750
distance d_746_750, (resi 292 and name OE1+OE2+OD1+OD2), (resi 296 and name NZ), cutoff=5
set dash_color, dark_gray, d_746_750
set dash_gap, 0.25, d_746_750
set dash_width, 1.5, d_746_750
hide labels, d_746_750

ray 2400, 1800
png thesis/ch3_mogrn/fig_3.1_mogrn_comparison/fig_3.1b_c1c2_set1_schiff.png, dpi=300

hide sticks, set1_schiff
hide dashes, d_345_750
hide dashes, d_746_750

# =============================================================================
# SET2_PROTON — Proton pathway / TM3 motif (E162, T166, I170, H173)
# =============================================================================
color backbone, all_grn
show sticks, set2_proton
color tm3_color, grn_3_45 or grn_3_49 or grn_3_53 or grn_3_56
set stick_radius, 0.15, set2_proton

ray 2400, 1800
png thesis/ch3_mogrn/fig_3.1_mogrn_comparison/fig_3.1b_c1c2_set2_proton.png, dpi=300

hide sticks, set2_proton

# =============================================================================
# SET3_DCGATE — DC gate (C167, D195)
# =============================================================================
color backbone, all_grn
show sticks, set3_dcgate
color tm3_color, grn_3_50
color tm4_color, grn_4_47
set stick_radius, 0.15, set3_dcgate
distance d_dcgate, (resi 167 and name SG+OG1+OG), (resi 195 and name OD1+OD2), cutoff=6
set dash_color, dark_gray, d_dcgate
set dash_gap, 0.25, d_dcgate
set dash_width, 1.5, d_dcgate
hide labels, d_dcgate

ray 2400, 1800
png thesis/ch3_mogrn/fig_3.1_mogrn_comparison/fig_3.1b_c1c2_set3_dcgate.png, dpi=300

hide sticks, set3_dcgate
hide dashes, d_dcgate

# =============================================================================
# SET4_POCKET — Binding pocket (W163, V214, F217, W262, F265)
# =============================================================================
color backbone, all_grn
show sticks, set4_pocket
color tm3_color, grn_3_46
color tm5_color, grn_5_44 or grn_5_47
color tm6_color, grn_6_50 or grn_6_53
set stick_radius, 0.15, set4_pocket

ray 2400, 1800
png thesis/ch3_mogrn/fig_3.1_mogrn_comparison/fig_3.1b_c1c2_set4_pocket.png, dpi=300

hide sticks, set4_pocket

# =============================================================================
# SET5_TUNING — Spectral tuning switches (I170, I199, G202, P266, S295)
# =============================================================================
color backbone, all_grn
show sticks, set5_tuning
color tm3_color, grn_3_53
color tm4_color, grn_4_51 or grn_4_54
color tm6_color, grn_6_54
color tm7_color, grn_7_49
set stick_radius, 0.15, set5_tuning

ray 2400, 1800
png thesis/ch3_mogrn/fig_3.1_mogrn_comparison/fig_3.1b_c1c2_set5_tuning.png, dpi=300

hide sticks, set5_tuning

# =============================================================================
# SET6_CHANNEL — Channel gate (E121, E122)
# =============================================================================
color backbone, all_grn
show sticks, set6_channel
color tm2_color, grn_2_46 or grn_2_47
set stick_radius, 0.15, set6_channel

ray 2400, 1800
png thesis/ch3_mogrn/fig_3.1_mogrn_comparison/fig_3.1b_c1c2_set6_channel.png, dpi=300

hide sticks, set6_channel

# =============================================================================
# ALL SETS combined — overview render
# =============================================================================
show sticks, all_grn
color tm2_color, grn_2_46
color tm2_color, grn_2_47
color tm3_color, grn_3_42
color tm3_color, grn_3_45
color tm3_color, grn_3_46
color tm3_color, grn_3_49
color tm3_color, grn_3_50
color tm3_color, grn_3_53
color tm3_color, grn_3_56
color tm4_color, grn_4_47
color tm4_color, grn_4_51
color tm4_color, grn_4_54
color tm5_color, grn_5_44
color tm5_color, grn_5_47
color tm6_color, grn_6_50
color tm6_color, grn_6_53
color tm6_color, grn_6_54
color tm7_color, grn_7_46
color tm7_color, grn_7_49
color tm7_color, grn_7_50
set stick_radius, 0.15, all_grn

ray 2400, 1800
png thesis/ch3_mogrn/fig_3.1_mogrn_comparison/fig_3.1b_c1c2_all_positions.png, dpi=300

# =============================================================================
# Save session
# =============================================================================
deselect
save thesis/ch3_mogrn/fig_3.1_mogrn_comparison/fig_3.1b_c1c2_mogrn_microswitches.pse

print("")
print("=" * 60)
print("Figure 3.1b (C1C2) — MO-GRN Functional Sets on 3UG9")
print("=" * 60)
print("  Schiff base & counterions: R159, E162, D292, K296")
print("  Proton pathway / TM3 motif: E162, T166, I170, H173")
print("  DC gate: C167, D195")
print("  Binding pocket: W163, V214, F217, W262, F265")
print("  Spectral tuning switches: I170, I199, G202, P266, S295")
print("  Channel gate: E121, E122")
print("=" * 60)