# Figure 3.1d (Heliorhodopsin) — MO-GRN Functional Sets on 6IS6
# ===========================================================================
# Generated by generate_mogrn_microswitches.py from mo_ref.csv annotations.
# All 20 key MO-GRN positions, 6 functional sets, no labels.
#
# Residue mapping (MO-GRN → Heliorhodopsin residue):
#   2.46 → L70
#   2.47 → V71
#   3.42 → R105
#   3.45 → E108
#   3.46 → Y109
#   3.49 → S112
#   3.50 → A113
#   3.53 → M116
#   3.56 → I119
#   4.47 → T139
#   4.51 → N143
#   4.54 → G146
#   5.44 → W161
#   5.47 → Y164
#   6.50 → F203
#   6.53 → F206
#   6.54 → A207
#   7.46 → S234
#   7.49 → A237
#   7.50 → K238
#
# Usage:
#   pymol mogrn_microswitches_6is6.pml
# ===========================================================================

# Load shared colorscales (colors + render settings)
@thesis/shared/colorscales_pymol.pml

# --- TM helix colors (spectral scheme) ---
set_color tm2_color, [0.239, 0.353, 0.502]
set_color tm3_color, [0.271, 0.482, 0.420]
set_color tm4_color, [0.416, 0.600, 0.306]
set_color tm5_color, [0.831, 0.627, 0.235]
set_color tm6_color, [0.737, 0.424, 0.145]
set_color tm7_color, [0.757, 0.400, 0.420]

# =============================================================================
# Load structure
# =============================================================================
fetch 6IS6, her, type=pdb, async=0
remove solvent
remove her and not chain A

# Backbone: gray, transparent
hide everything
show cartoon, her and chain A and polymer
color backbone, her
set cartoon_transparency, 0.75, her

# Retinal chromophore (always visible)
select retinal, her and chain A and resn RET
show sticks, retinal
color retinal_rust, retinal
set stick_radius, 0.20, retinal

# =============================================================================
# Define ALL residue selections (by MO-GRN position)
# =============================================================================
select grn_2_46, her and chain A and resi 70
select grn_2_47, her and chain A and resi 71
select grn_3_42, her and chain A and resi 105
select grn_3_45, her and chain A and resi 108
select grn_3_46, her and chain A and resi 109
select grn_3_49, her and chain A and resi 112
select grn_3_50, her and chain A and resi 113
select grn_3_53, her and chain A and resi 116
select grn_3_56, her and chain A and resi 119
select grn_4_47, her and chain A and resi 139
select grn_4_51, her and chain A and resi 143
select grn_4_54, her and chain A and resi 146
select grn_5_44, her and chain A and resi 161
select grn_5_47, her and chain A and resi 164
select grn_6_50, her and chain A and resi 203
select grn_6_53, her and chain A and resi 206
select grn_6_54, her and chain A and resi 207
select grn_7_46, her and chain A and resi 234
select grn_7_49, her and chain A and resi 237
select grn_7_50, her and chain A and resi 238

# =============================================================================
# Define functional sets
# =============================================================================
select set1_schiff, grn_3_42 or grn_3_45 or grn_7_46 or grn_7_50
select set2_proton, grn_3_45 or grn_3_49 or grn_3_53 or grn_3_56
select set3_dcgate, grn_3_50 or grn_4_47
select set4_pocket, grn_3_46 or grn_5_44 or grn_5_47 or grn_6_50 or grn_6_53
select set5_tuning, grn_3_53 or grn_4_51 or grn_4_54 or grn_6_54 or grn_7_49
select set6_channel, grn_2_46 or grn_2_47
select all_grn, set1_schiff or set2_proton or set3_dcgate or set4_pocket or set5_tuning or set6_channel

# Start with all sticks hidden
hide sticks, all_grn
deselect

# =============================================================================
# Camera
# =============================================================================
set_view (\
    -0.611530423,    0.048888613,    0.789709210,\
     0.060476568,    0.998057067,   -0.014955943,\
    -0.788905144,    0.038611859,   -0.613296807,\
     0.000003062,    0.000006479, -193.146240234,\
    -0.785787582,  -29.144750595,   12.587509155,\
   174.106903076,  212.184936523,   20.000000000 )

# =============================================================================
# SET1_SCHIFF — Schiff base & counterions (R105, E108, S234, K238)
# =============================================================================
color backbone, all_grn
show sticks, set1_schiff
color tm3_color, grn_3_42 or grn_3_45
color tm7_color, grn_7_46 or grn_7_50
set stick_radius, 0.15, set1_schiff
distance d_345_750, (resi 108 and name OE1+OE2+OD1+OD2), (resi 238 and name NZ), cutoff=5
set dash_color, dark_gray, d_345_750
set dash_gap, 0.25, d_345_750
set dash_width, 1.5, d_345_750
hide labels, d_345_750
distance d_746_750, (resi 234 and name OE1+OE2+OD1+OD2), (resi 238 and name NZ), cutoff=5
set dash_color, dark_gray, d_746_750
set dash_gap, 0.25, d_746_750
set dash_width, 1.5, d_746_750
hide labels, d_746_750

ray 2400, 1800
png thesis/ch3_mogrn/fig_3.1_mogrn_comparison/fig_3.1d_her_set1_schiff.png, dpi=300

hide sticks, set1_schiff
hide dashes, d_345_750
hide dashes, d_746_750

# =============================================================================
# SET2_PROTON — Proton pathway / TM3 motif (E108, S112, M116, I119)
# =============================================================================
color backbone, all_grn
show sticks, set2_proton
color tm3_color, grn_3_45 or grn_3_49 or grn_3_53 or grn_3_56
set stick_radius, 0.15, set2_proton

ray 2400, 1800
png thesis/ch3_mogrn/fig_3.1_mogrn_comparison/fig_3.1d_her_set2_proton.png, dpi=300

hide sticks, set2_proton

# =============================================================================
# SET3_DCGATE — DC gate (A113, T139)
# =============================================================================
color backbone, all_grn
show sticks, set3_dcgate
color tm3_color, grn_3_50
color tm4_color, grn_4_47
set stick_radius, 0.15, set3_dcgate
distance d_dcgate, (resi 113 and name SG+OG1+OG), (resi 139 and name OD1+OD2+OE1+OE2), cutoff=6
set dash_color, dark_gray, d_dcgate
set dash_gap, 0.25, d_dcgate
set dash_width, 1.5, d_dcgate
hide labels, d_dcgate

ray 2400, 1800
png thesis/ch3_mogrn/fig_3.1_mogrn_comparison/fig_3.1d_her_set3_dcgate.png, dpi=300

hide sticks, set3_dcgate
hide dashes, d_dcgate

# =============================================================================
# SET4_POCKET — Binding pocket (Y109, W161, Y164, F203, F206)
# =============================================================================
color backbone, all_grn
show sticks, set4_pocket
color tm3_color, grn_3_46
color tm5_color, grn_5_44 or grn_5_47
color tm6_color, grn_6_50 or grn_6_53
set stick_radius, 0.15, set4_pocket

ray 2400, 1800
png thesis/ch3_mogrn/fig_3.1_mogrn_comparison/fig_3.1d_her_set4_pocket.png, dpi=300

hide sticks, set4_pocket

# =============================================================================
# SET5_TUNING — Spectral tuning switches (M116, N143, G146, A207, A237)
# =============================================================================
color backbone, all_grn
show sticks, set5_tuning
color tm3_color, grn_3_53
color tm4_color, grn_4_51 or grn_4_54
color tm6_color, grn_6_54
color tm7_color, grn_7_49
set stick_radius, 0.15, set5_tuning

ray 2400, 1800
png thesis/ch3_mogrn/fig_3.1_mogrn_comparison/fig_3.1d_her_set5_tuning.png, dpi=300

hide sticks, set5_tuning

# =============================================================================
# SET6_CHANNEL — Channel gate (L70, V71)
# =============================================================================
color backbone, all_grn
show sticks, set6_channel
color tm2_color, grn_2_46 or grn_2_47
set stick_radius, 0.15, set6_channel

ray 2400, 1800
png thesis/ch3_mogrn/fig_3.1_mogrn_comparison/fig_3.1d_her_set6_channel.png, dpi=300

hide sticks, set6_channel

# =============================================================================
# ALL SETS combined — overview render
# =============================================================================
show sticks, all_grn
color tm2_color, grn_2_46
color tm2_color, grn_2_47
color tm3_color, grn_3_42
color tm3_color, grn_3_45
color tm3_color, grn_3_46
color tm3_color, grn_3_49
color tm3_color, grn_3_50
color tm3_color, grn_3_53
color tm3_color, grn_3_56
color tm4_color, grn_4_47
color tm4_color, grn_4_51
color tm4_color, grn_4_54
color tm5_color, grn_5_44
color tm5_color, grn_5_47
color tm6_color, grn_6_50
color tm6_color, grn_6_53
color tm6_color, grn_6_54
color tm7_color, grn_7_46
color tm7_color, grn_7_49
color tm7_color, grn_7_50
set stick_radius, 0.15, all_grn

ray 2400, 1800
png thesis/ch3_mogrn/fig_3.1_mogrn_comparison/fig_3.1d_her_all_positions.png, dpi=300

# =============================================================================
# Save session
# =============================================================================
deselect
save thesis/ch3_mogrn/fig_3.1_mogrn_comparison/fig_3.1d_her_mogrn_microswitches.pse

print("")
print("=" * 60)
print("Figure 3.1d (Heliorhodopsin) — MO-GRN Functional Sets on 6IS6")
print("=" * 60)
print("  Schiff base & counterions: R105, E108, S234, K238")
print("  Proton pathway / TM3 motif: E108, S112, M116, I119")
print("  DC gate: A113, T139")
print("  Binding pocket: Y109, W161, Y164, F203, F206")
print("  Spectral tuning switches: M116, N143, G146, A207, A237")
print("  Channel gate: L70, V71")
print("=" * 60)