#!/usr/bin/env python3
"""Generate MO-GRN microswitch PML script for C1C2 (3UG9).

Reads MO-GRN annotations from the reference table and generates a PyMOL
script with all 6 functional sets mapped onto C1C2, analogous to the bR
version (mogrn_microswitches.pml).

Usage:
    python mogrn_microswitches_c1c2.py
    # Then run the generated PML:
    pymol mogrn_microswitches_c1c2.pml
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

THESIS_DIR = Path(__file__).resolve().parent.parent.parent
PROJECT_ROOT = THESIS_DIR.parent
GRN_CSV = PROJECT_ROOT / "data" / "grn" / "reference" / "mo_ref.csv"
OUTDIR = Path(__file__).resolve().parent

ENTITY = "3UG9"
CHAIN = "A"

# The 20 key MO-GRN positions
MO_GRN_POSITIONS = [
    "2.46", "2.47",
    "3.42", "3.45", "3.46", "3.49", "3.50", "3.53", "3.56",
    "4.47", "4.51", "4.54",
    "5.44", "5.47",
    "6.50", "6.53", "6.54",
    "7.46", "7.49", "7.50",
]

# Functional sets
SETS = {
    "set1_schiff":  {"positions": ["3.42", "3.45", "7.46", "7.50"],
                     "name": "Schiff base & counterions"},
    "set2_proton":  {"positions": ["3.45", "3.49", "3.53", "3.56"],
                     "name": "Proton pathway / TM3 motif"},
    "set3_dcgate":  {"positions": ["3.50", "4.47"],
                     "name": "DC gate"},
    "set4_pocket":  {"positions": ["3.46", "5.44", "5.47", "6.50", "6.53"],
                     "name": "Binding pocket"},
    "set5_tuning":  {"positions": ["3.53", "4.51", "4.54", "6.54", "7.49"],
                     "name": "Spectral tuning switches"},
    "set6_channel": {"positions": ["2.46", "2.47"],
                     "name": "Channel gate"},
}


def load_grn_mapping(entity_id: str) -> dict[str, tuple[str, int]]:
    """Load MO-GRN → (amino_acid, residue_number) mapping from mo_ref.csv."""
    df = pd.read_csv(GRN_CSV, index_col=0)
    df.columns = df.columns.astype(str)
    cols = list(df.columns)

    if entity_id not in df.index:
        raise ValueError(f"{entity_id} not found in {GRN_CSV}")

    row = df.loc[entity_id]
    mapping = {}
    for pos in MO_GRN_POSITIONS:
        # Handle trailing zero: "3.50" → "3.5" in CSV
        col = pos if pos in cols else str(float(pos))
        v = str(row.get(col, "-"))
        if v not in ("nan", "-", "", "None"):
            aa = v[0]
            resnum = int(v[1:])
            mapping[pos] = (aa, resnum)
        else:
            print(f"  WARNING: {entity_id} has no annotation at {pos}")
    return mapping


def grn_to_helix(pos: str) -> str:
    return pos.split(".")[0]


def generate_pml(mapping: dict[str, tuple[str, int]]) -> str:
    """Generate the PML script content."""
    lines = []

    def w(s=""):
        lines.append(s)

    w(f"# Figure 3.1b (C1C2) — MO-GRN Functional Sets on C1C2 ({ENTITY})")
    w("# ===========================================================================")
    w("# Generated by mogrn_microswitches_c1c2.py from mo_ref.csv annotations.")
    w("# All 20 key MO-GRN positions, 6 functional sets, no labels.")
    w("#")
    w("# Residue mapping (MO-GRN → C1C2 residue):")
    for pos in MO_GRN_POSITIONS:
        if pos in mapping:
            aa, rn = mapping[pos]
            w(f"#   {pos} → {aa}{rn}")
    w("#")
    w("# Usage:")
    w("#   pymol mogrn_microswitches_c1c2.pml")
    w("# ===========================================================================")
    w()
    w("# Load shared colorscales (colors + render settings)")
    w("@thesis/shared/colorscales_pymol.pml")
    w()
    w("# --- TM helix colors (spectral scheme) ---")
    w("set_color tm2_color, [0.239, 0.353, 0.502]")
    w("set_color tm3_color, [0.271, 0.482, 0.420]")
    w("set_color tm4_color, [0.416, 0.600, 0.306]")
    w("set_color tm5_color, [0.831, 0.627, 0.235]")
    w("set_color tm6_color, [0.737, 0.424, 0.145]")
    w("set_color tm7_color, [0.757, 0.400, 0.420]")
    w()

    # Load structure
    w("# =============================================================================")
    w("# Load structure")
    w("# =============================================================================")
    w(f"fetch {ENTITY}, c1c2, type=pdb, async=0")
    w("remove solvent")
    w(f"remove c1c2 and not chain {CHAIN}")
    w()
    w("# Backbone: gray, transparent")
    w("hide everything")
    w(f"show cartoon, c1c2 and chain {CHAIN} and polymer")
    w("color backbone, c1c2")
    w("set cartoon_transparency, 0.75, c1c2")
    w()

    # Retinal
    w("# Retinal chromophore (always visible)")
    w(f"select retinal, c1c2 and chain {CHAIN} and resn RET")
    w("show sticks, retinal")
    w("color retinal_rust, retinal")
    w("set stick_radius, 0.20, retinal")
    w()

    # Define all selections
    w("# =============================================================================")
    w("# Define ALL residue selections (by MO-GRN position)")
    w("# =============================================================================")
    for pos in MO_GRN_POSITIONS:
        if pos in mapping:
            aa, rn = mapping[pos]
            grn_safe = pos.replace(".", "_")
            w(f"select grn_{grn_safe}, c1c2 and chain {CHAIN} and resi {rn}")
    w()

    # Define functional sets
    w("# =============================================================================")
    w("# Define functional sets")
    w("# =============================================================================")
    for set_key, set_info in SETS.items():
        members = [f"grn_{p.replace('.', '_')}" for p in set_info["positions"] if p in mapping]
        w(f"select {set_key}, {' or '.join(members)}")

    # all_grn
    all_sets = " or ".join(SETS.keys())
    w(f"select all_grn, {all_sets}")
    w()
    w("# Start with all sticks hidden")
    w("hide sticks, all_grn")
    w("deselect")
    w()

    # Camera
    w("# =============================================================================")
    w("# Camera")
    w("# =============================================================================")
    w("set_view (\\")
    w("    -0.963549674,   -0.143934369,   -0.225513399,\\")
    w("     0.149556443,   -0.988720417,   -0.007953573,\\")
    w("    -0.221825153,   -0.041390404,    0.974206805,\\")
    w("     0.000002506,    0.000059575, -263.628967285,\\")
    w("     7.338849068,   34.503849030,   13.155744553,\\")
    w("   208.342391968,  318.911865234,   20.000000000 )")
    w()

    # Render each set
    outdir = str(OUTDIR)
    for set_key, set_info in SETS.items():
        positions = set_info["positions"]
        name = set_info["name"]
        residues = [f"{mapping[p][0]}{mapping[p][1]}" for p in positions if p in mapping]

        w("# =============================================================================")
        w(f"# {set_key.upper()} — {name} ({', '.join(residues)})")
        w("# =============================================================================")
        w("color backbone, all_grn")
        w(f"show sticks, {set_key}")

        # Color by TM helix
        helices_in_set: dict[str, list[str]] = {}
        for p in positions:
            if p in mapping:
                h = grn_to_helix(p)
                helices_in_set.setdefault(h, []).append(f"grn_{p.replace('.', '_')}")
        for h, sels in helices_in_set.items():
            w(f"color tm{h}_color, {' or '.join(sels)}")

        w(f"set stick_radius, 0.15, {set_key}")

        # Special interactions for specific sets
        if set_key == "set1_schiff":
            # Counterion-Schiff base dashes
            if "3.45" in mapping and "7.50" in mapping:
                rn_345 = mapping["3.45"][1]
                rn_750 = mapping["7.50"][1]
                w(f"distance d_345_750, (resi {rn_345} and name OE1+OE2+OD1+OD2), (resi {rn_750} and name NZ), cutoff=5")
                w("set dash_color, dark_gray, d_345_750")
                w("set dash_gap, 0.25, d_345_750")
                w("set dash_width, 1.5, d_345_750")
                w("hide labels, d_345_750")
            if "7.46" in mapping and "7.50" in mapping:
                rn_746 = mapping["7.46"][1]
                rn_750 = mapping["7.50"][1]
                w(f"distance d_746_750, (resi {rn_746} and name OE1+OE2+OD1+OD2), (resi {rn_750} and name NZ), cutoff=5")
                w("set dash_color, dark_gray, d_746_750")
                w("set dash_gap, 0.25, d_746_750")
                w("set dash_width, 1.5, d_746_750")
                w("hide labels, d_746_750")

        if set_key == "set3_dcgate":
            if "3.50" in mapping and "4.47" in mapping:
                rn_350 = mapping["3.50"][1]
                rn_447 = mapping["4.47"][1]
                w(f"distance d_dcgate, (resi {rn_350} and name SG+OG1+OG), (resi {rn_447} and name OD1+OD2), cutoff=6")
                w("set dash_color, dark_gray, d_dcgate")
                w("set dash_gap, 0.25, d_dcgate")
                w("set dash_width, 1.5, d_dcgate")
                w("hide labels, d_dcgate")

        # Render
        short_name = set_key.replace("set", "").replace("_", "_", 1)
        w()
        w("ray 2400, 1800")
        w(f"png {outdir}/fig_3.1b_c1c2_{set_key}.png, dpi=300")
        w()
        w(f"hide sticks, {set_key}")

        # Hide dashes if any
        if set_key == "set1_schiff":
            w("hide dashes, d_345_750")
            w("hide dashes, d_746_750")
        if set_key == "set3_dcgate":
            w("hide dashes, d_dcgate")
        w()

    # All combined
    w("# =============================================================================")
    w("# ALL SETS combined — overview render")
    w("# =============================================================================")
    w("show sticks, all_grn")
    for pos in MO_GRN_POSITIONS:
        if pos in mapping:
            h = grn_to_helix(pos)
            grn_safe = pos.replace(".", "_")
            w(f"color tm{h}_color, grn_{grn_safe}")
    w("set stick_radius, 0.15, all_grn")
    w()
    w("ray 2400, 1800")
    w(f"png {outdir}/fig_3.1b_c1c2_all_positions.png, dpi=300")
    w()

    # Save session
    w("# =============================================================================")
    w("# Save session")
    w("# =============================================================================")
    w("deselect")
    w(f"save {outdir}/fig_3.1b_c1c2_mogrn_microswitches.pse")
    w()

    # Summary
    w('print("")')
    w('print("=" * 60)')
    w(f'print("Figure 3.1b (C1C2) — MO-GRN Functional Sets on {ENTITY}")')
    w('print("=" * 60)')
    for set_key, set_info in SETS.items():
        residues = [f"{mapping[p][0]}{mapping[p][1]}" for p in set_info["positions"] if p in mapping]
        w(f'print("  {set_info["name"]}: {", ".join(residues)}")')
    w('print("=" * 60)')

    return "\n".join(lines)


def main() -> int:
    print("=" * 70)
    print(f"Generating MO-GRN microswitch PML for {ENTITY} (C1C2)")
    print("=" * 70)

    mapping = load_grn_mapping(ENTITY)
    print(f"\nLoaded {len(mapping)} MO-GRN position mappings:\n")

    for pos in MO_GRN_POSITIONS:
        if pos in mapping:
            aa, rn = mapping[pos]
            print(f"  {pos:>5s} → {aa}{rn}")

    pml_content = generate_pml(mapping)
    out_pml = OUTDIR / "mogrn_microswitches_c1c2.pml"
    out_pml.write_text(pml_content)
    print(f"\nSaved: {out_pml}")
    print("Run with: pymol mogrn_microswitches_c1c2.pml")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
