# Figure 3.1e (Bestrhodopsin) — MO-GRN Functional Sets on 7PL9
# ===========================================================================
# Generated by generate_mogrn_microswitches.py from mo_ref.csv annotations.
# All 20 key MO-GRN positions, 6 functional sets, no labels.
#
# Residue mapping (MO-GRN → Bestrhodopsin residue):
#   2.46 → V561
#   2.47 → L562
#   3.42 → R600
#   3.45 → E603
#   3.46 → W604
#   3.49 → D607
#   3.50 → A608
#   3.53 → L611
#   3.56 → L614
#   4.47 → T634
#   4.51 → M638
#   4.54 → G641
#   5.44 → W654
#   5.47 → L657
#   6.50 → W702
#   6.53 → Y705
#   6.54 → G706
#   7.46 → D732
#   7.49 → M735
#   7.50 → K736
#
# Usage:
#   pymol mogrn_microswitches_7pl9.pml
# ===========================================================================

# Load shared colorscales (colors + render settings)
@thesis/shared/colorscales_pymol.pml

# --- TM helix colors (spectral scheme) ---
set_color tm2_color, [0.239, 0.353, 0.502]
set_color tm3_color, [0.271, 0.482, 0.420]
set_color tm4_color, [0.416, 0.600, 0.306]
set_color tm5_color, [0.831, 0.627, 0.235]
set_color tm6_color, [0.737, 0.424, 0.145]
set_color tm7_color, [0.757, 0.400, 0.420]

# =============================================================================
# Load structure
# =============================================================================
fetch 7PL9, bestr, type=pdb, async=0
remove solvent
remove bestr and not chain A

# Remove the bestrophin channel domain (residues ~1-500), keep only the
# rhodopsin 7TM domain (residues ~510-750) for visual consistency with
# the other rhodopsin panels.
remove bestr and chain A and not resi 501-758

# Backbone: gray, transparent
hide everything
show cartoon, bestr and chain A and polymer
color backbone, bestr
set cartoon_transparency, 0.75, bestr

# Retinal chromophore (always visible)
select retinal, bestr and chain A and resn RET
show sticks, retinal
color retinal_rust, retinal
set stick_radius, 0.20, retinal

# =============================================================================
# Define ALL residue selections (by MO-GRN position)
# =============================================================================
select grn_2_46, bestr and chain A and resi 561
select grn_2_47, bestr and chain A and resi 562
select grn_3_42, bestr and chain A and resi 600
select grn_3_45, bestr and chain A and resi 603
select grn_3_46, bestr and chain A and resi 604
select grn_3_49, bestr and chain A and resi 607
select grn_3_50, bestr and chain A and resi 608
select grn_3_53, bestr and chain A and resi 611
select grn_3_56, bestr and chain A and resi 614
select grn_4_47, bestr and chain A and resi 634
select grn_4_51, bestr and chain A and resi 638
select grn_4_54, bestr and chain A and resi 641
select grn_5_44, bestr and chain A and resi 654
select grn_5_47, bestr and chain A and resi 657
select grn_6_50, bestr and chain A and resi 702
select grn_6_53, bestr and chain A and resi 705
select grn_6_54, bestr and chain A and resi 706
select grn_7_46, bestr and chain A and resi 732
select grn_7_49, bestr and chain A and resi 735
select grn_7_50, bestr and chain A and resi 736

# =============================================================================
# Define functional sets
# =============================================================================
select set1_schiff, grn_3_42 or grn_3_45 or grn_7_46 or grn_7_50
select set2_proton, grn_3_45 or grn_3_49 or grn_3_53 or grn_3_56
select set3_dcgate, grn_3_50 or grn_4_47
select set4_pocket, grn_3_46 or grn_5_44 or grn_5_47 or grn_6_50 or grn_6_53
select set5_tuning, grn_3_53 or grn_4_51 or grn_4_54 or grn_6_54 or grn_7_49
select set6_channel, grn_2_46 or grn_2_47
select all_grn, set1_schiff or set2_proton or set3_dcgate or set4_pocket or set5_tuning or set6_channel

# Start with all sticks hidden
hide sticks, all_grn
deselect

# =============================================================================
# Camera
# =============================================================================
set_view (\
    -0.198144615,    0.166126832,    0.965991616,\
     0.926263034,   -0.290598661,    0.239969894,\
     0.320583403,    0.942309201,   -0.096298940,\
     0.000067424,   -0.000846565, -205.371597290,\
   125.286468506,  195.884613037,  181.827774048,\
   -81.680404663,  492.422912598,   20.000000000 )

# =============================================================================
# SET1_SCHIFF — Schiff base & counterions (R600, E603, D732, K736)
# =============================================================================
color backbone, all_grn
show sticks, set1_schiff
color tm3_color, grn_3_42 or grn_3_45
color tm7_color, grn_7_46 or grn_7_50
set stick_radius, 0.15, set1_schiff
distance d_345_750, (resi 603 and name OE1+OE2+OD1+OD2), (resi 736 and name NZ), cutoff=5
set dash_color, dark_gray, d_345_750
set dash_gap, 0.25, d_345_750
set dash_width, 1.5, d_345_750
hide labels, d_345_750
distance d_746_750, (resi 732 and name OE1+OE2+OD1+OD2), (resi 736 and name NZ), cutoff=5
set dash_color, dark_gray, d_746_750
set dash_gap, 0.25, d_746_750
set dash_width, 1.5, d_746_750
hide labels, d_746_750

ray 2400, 1800
png thesis/ch3_mogrn/fig_3.1_mogrn_comparison/fig_3.1e_bestr_set1_schiff.png, dpi=300

hide sticks, set1_schiff
hide dashes, d_345_750
hide dashes, d_746_750

# =============================================================================
# SET2_PROTON — Proton pathway / TM3 motif (E603, D607, L611, L614)
# =============================================================================
color backbone, all_grn
show sticks, set2_proton
color tm3_color, grn_3_45 or grn_3_49 or grn_3_53 or grn_3_56
set stick_radius, 0.15, set2_proton

ray 2400, 1800
png thesis/ch3_mogrn/fig_3.1_mogrn_comparison/fig_3.1e_bestr_set2_proton.png, dpi=300

hide sticks, set2_proton

# =============================================================================
# SET3_DCGATE — DC gate (A608, T634)
# =============================================================================
color backbone, all_grn
show sticks, set3_dcgate
color tm3_color, grn_3_50
color tm4_color, grn_4_47
set stick_radius, 0.15, set3_dcgate
distance d_dcgate, (resi 608 and name SG+OG1+OG), (resi 634 and name OD1+OD2+OE1+OE2), cutoff=6
set dash_color, dark_gray, d_dcgate
set dash_gap, 0.25, d_dcgate
set dash_width, 1.5, d_dcgate
hide labels, d_dcgate

ray 2400, 1800
png thesis/ch3_mogrn/fig_3.1_mogrn_comparison/fig_3.1e_bestr_set3_dcgate.png, dpi=300

hide sticks, set3_dcgate
hide dashes, d_dcgate

# =============================================================================
# SET4_POCKET — Binding pocket (W604, W654, L657, W702, Y705)
# =============================================================================
color backbone, all_grn
show sticks, set4_pocket
color tm3_color, grn_3_46
color tm5_color, grn_5_44 or grn_5_47
color tm6_color, grn_6_50 or grn_6_53
set stick_radius, 0.15, set4_pocket

ray 2400, 1800
png thesis/ch3_mogrn/fig_3.1_mogrn_comparison/fig_3.1e_bestr_set4_pocket.png, dpi=300

hide sticks, set4_pocket

# =============================================================================
# SET5_TUNING — Spectral tuning switches (L611, M638, G641, G706, M735)
# =============================================================================
color backbone, all_grn
show sticks, set5_tuning
color tm3_color, grn_3_53
color tm4_color, grn_4_51 or grn_4_54
color tm6_color, grn_6_54
color tm7_color, grn_7_49
set stick_radius, 0.15, set5_tuning

ray 2400, 1800
png thesis/ch3_mogrn/fig_3.1_mogrn_comparison/fig_3.1e_bestr_set5_tuning.png, dpi=300

hide sticks, set5_tuning

# =============================================================================
# SET6_CHANNEL — Channel gate (V561, L562)
# =============================================================================
color backbone, all_grn
show sticks, set6_channel
color tm2_color, grn_2_46 or grn_2_47
set stick_radius, 0.15, set6_channel

ray 2400, 1800
png thesis/ch3_mogrn/fig_3.1_mogrn_comparison/fig_3.1e_bestr_set6_channel.png, dpi=300

hide sticks, set6_channel

# =============================================================================
# ALL SETS combined — overview render
# =============================================================================
show sticks, all_grn
color tm2_color, grn_2_46
color tm2_color, grn_2_47
color tm3_color, grn_3_42
color tm3_color, grn_3_45
color tm3_color, grn_3_46
color tm3_color, grn_3_49
color tm3_color, grn_3_50
color tm3_color, grn_3_53
color tm3_color, grn_3_56
color tm4_color, grn_4_47
color tm4_color, grn_4_51
color tm4_color, grn_4_54
color tm5_color, grn_5_44
color tm5_color, grn_5_47
color tm6_color, grn_6_50
color tm6_color, grn_6_53
color tm6_color, grn_6_54
color tm7_color, grn_7_46
color tm7_color, grn_7_49
color tm7_color, grn_7_50
set stick_radius, 0.15, all_grn

ray 2400, 1800
png thesis/ch3_mogrn/fig_3.1_mogrn_comparison/fig_3.1e_bestr_all_positions.png, dpi=300

# =============================================================================
# Save session
# =============================================================================
deselect
save thesis/ch3_mogrn/fig_3.1_mogrn_comparison/fig_3.1e_bestr_mogrn_microswitches.pse

print("")
print("=" * 60)
print("Figure 3.1e (Bestrhodopsin) — MO-GRN Functional Sets on 7PL9")
print("=" * 60)
print("  Schiff base & counterions: R600, E603, D732, K736")
print("  Proton pathway / TM3 motif: E603, D607, L611, L614")
print("  DC gate: A608, T634")
print("  Binding pocket: W604, W654, L657, W702, Y705")
print("  Spectral tuning switches: L611, M638, G641, G706, M735")
print("  Channel gate: V561, L562")
print("=" * 60)