"""Core data structures describing model IO requirements and execution."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Union


@dataclass
class ArtifactSpec:
    """Declarative description of an input or output artifact."""

    name: str
    kind: str
    provider: str
    format: Optional[str] = None
    optional: bool = False
    params: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ExecutionSpec:
    """Describe how a model should be executed."""

    mode: str  # e.g. "external_config" or "runtime"
    entrypoint: Optional[str] = None
    environment: Dict[str, Any] = field(default_factory=dict)
    expected_config: Optional[str] = None


@dataclass
class ModelCard:
    """High-level descriptor combining IO specs and execution metadata."""

    name: str
    version: str
    description: str
    execution: ExecutionSpec
    input_spec: List[ArtifactSpec] = field(default_factory=list)
    output_spec: List[ArtifactSpec] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ArtifactBundle:
    """Resolved artifact available on disk with extra metadata."""

    spec: ArtifactSpec
    path: Path
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class PreparedJob:
    """Command/configuration payload for externally executed models."""

    command: List[str]
    working_dir: Path
    artifacts: List[ArtifactBundle]
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class RuntimeResult:
    """Outputs generated by in-process model execution."""

    outputs: Dict[str, Any]
    artifacts: List[ArtifactBundle]
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ModelInvocation:
    """Unified response from ModelManager after preparing/executing a model."""

    model: str
    card: ModelCard
    job: Optional[PreparedJob] = None
    runtime: Optional[RuntimeResult] = None
    inputs: List[ArtifactBundle] = field(default_factory=list)
    outputs: List[ArtifactBundle] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def is_external(self) -> bool:
        return self.job is not None

    def is_runtime(self) -> bool:
        return self.runtime is not None


@dataclass
class ModelBatch:
    """Lightweight container describing a batch of model inputs."""

    name: str
    model: str
    inputs: List[Dict[str, Any]] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "name": self.name,
            "model": self.model,
            "input_count": len(self.inputs),
            "inputs": self.inputs,
            "metadata": self.metadata,
        }
