# PyMOL script: Rhodopsin spectral tuning positions
# Generated by ProtOS GRNProcessor example
# Structure: 1U19 (bovine rhodopsin, inactive state)

# Load structure
fetch 1U19, rhodopsin
remove solvent
remove chain B  # Remove second copy in asymmetric unit

# Basic display settings
bg_color white
set ray_shadows, 0
set antialias, 2
set orthoscopic, 1

# Show protein as cartoon
hide everything
show cartoon, rhodopsin
color gray80, rhodopsin

# Color helices by TM number
color tv_blue, resi 34-64      # TM1
color tv_green, resi 71-100    # TM2
color tv_yellow, resi 107-139  # TM3
color tv_orange, resi 150-173  # TM4
color salmon, resi 200-230     # TM5
color hotpink, resi 247-277    # TM6
color purple, resi 286-309     # TM7

# Show retinal (RET)
show sticks, resn RET
color yellow, resn RET
set stick_radius, 0.2, resn RET

# Highlight spectral tuning positions

# Spectral tuning positions (affect lambda_max)
select spectral_tuning, resi 113+134+167+168+206+261+265+297 and chain A
show sticks, spectral_tuning
color red, spectral_tuning
set stick_radius, 0.15, spectral_tuning

# Label key positions
label resi 113 and name CA and chain A, "3.28"
label resi 134 and name CA and chain A, "3.49"
label resi 167 and name CA and chain A, "4.56"
label resi 168 and name CA and chain A, "4.57"
label resi 206 and name CA and chain A, "5.42"
label resi 261 and name CA and chain A, "6.44"
label resi 265 and name CA and chain A, "6.48"
label resi 297 and name CA and chain A, "7.43"

# Conserved x.50 positions
select conserved_x50, resi 55+83+135+161+215+267+303 and chain A
show spheres, conserved_x50 and name CA
color cyan, conserved_x50 and name CA
set sphere_scale, 0.4, conserved_x50

# Set view (side view of retinal binding pocket)
set_view (\
     0.891841531,    0.230044052,   -0.389945507,\
    -0.423283607,    0.694878459,   -0.581074119,\
     0.157373756,    0.683379889,    0.713048816,\
     0.000000000,    0.000000000, -120.000000000,\
    15.000000000,   25.000000000,   40.000000000,\
    80.000000000,  160.000000000,  -20.000000000 )

# Ray trace for publication
# ray 2400, 1800
# png grn_spectral_tuning.png, dpi=300

# Session info
print("Spectral tuning positions highlighted in RED")
print("Conserved x.50 positions shown as CYAN spheres")
print("Retinal shown in YELLOW sticks")
