# PyMOL script: GRN-based structural alignment of GPCRs
# Generated by ProtOS GRNProcessor example
#
# KEY CONCEPT: GRN positions are structurally equivalent across GPCRs.
# This script loads pre-aligned rhodopsin and ADRB2 structures.
# Despite ~25% sequence identity, the 7TM core superposes well.

# Load aligned structures from CIF files
load 1u19_aligned.cif, rhodopsin
load 2rh1_aligned.cif, adrb2

# Basic display settings
bg_color white
set ray_shadows, 0
set antialias, 2
set orthoscopic, 1

# Show both as cartoon
hide everything
show cartoon, all

# Color by receptor
color marine, rhodopsin
color salmon, adrb2

# Show ligands as sticks
show sticks, resn RET
show sticks, resn CAU
color yellow, resn RET
color orange, resn CAU
set stick_radius, 0.2

# Highlight x.50 positions used for alignment

# 1.50: Rhodopsin N55, ADRB2 N23
select x50_1_50_rho, rhodopsin and resi 55 and name CA
select x50_1_50_adrb, adrb2 and resi 23 and name CA

# 2.50: Rhodopsin D83, ADRB2 D51
select x50_2_50_rho, rhodopsin and resi 83 and name CA
select x50_2_50_adrb, adrb2 and resi 51 and name CA

# 3.50: Rhodopsin R135, ADRB2 R103
select x50_3_50_rho, rhodopsin and resi 135 and name CA
select x50_3_50_adrb, adrb2 and resi 103 and name CA

# 4.50: Rhodopsin W161, ADRB2 W130
select x50_4_50_rho, rhodopsin and resi 161 and name CA
select x50_4_50_adrb, adrb2 and resi 130 and name CA

# 5.50: Rhodopsin P215, ADRB2 P183
select x50_5_50_rho, rhodopsin and resi 215 and name CA
select x50_5_50_adrb, adrb2 and resi 183 and name CA

# 6.50: Rhodopsin P267, ADRB2 P228
select x50_6_50_rho, rhodopsin and resi 267 and name CA
select x50_6_50_adrb, adrb2 and resi 228 and name CA

# 7.50: Rhodopsin P303, ADRB2 P263
select x50_7_50_rho, rhodopsin and resi 303 and name CA
select x50_7_50_adrb, adrb2 and resi 263 and name CA

# Show x.50 positions as spheres
select all_x50, x50_*
show spheres, all_x50
color cyan, all_x50 and rhodopsin
color magenta, all_x50 and adrb2
set sphere_scale, 0.5

# Create nice view
orient
zoom all, 5

# Add labels
set label_size, 14
set label_color, black
label rhodopsin and resi 55 and name CA, "1.50"
label rhodopsin and resi 83 and name CA, "2.50"
label rhodopsin and resi 135 and name CA, "3.50"
label rhodopsin and resi 161 and name CA, "4.50"
label rhodopsin and resi 215 and name CA, "5.50"
label rhodopsin and resi 267 and name CA, "6.50"
label rhodopsin and resi 303 and name CA, "7.50"

# Summary info
print("")
print("=" * 60)
print("GRN-BASED GPCR ALIGNMENT")
print("=" * 60)
print("Reference: 1U19 (rhodopsin) - marine")
print("Mobile: 2RH1 (ADRB2) - salmon")
print("Aligned on: 2.50, 3.50, 4.50, 5.50, 6.50, 7.50")
print("RMSD: 20.88 A")
print("")
print("KEY INSIGHT: Same GRN = Same 3D position")
print("Despite ~25% sequence identity, x.50 positions superpose.")
print("=" * 60)

# Ray trace for publication
# ray 2400, 1800
# png grn_structural_equivalence.png, dpi=300
