#!/usr/bin/env python3
"""Prepare GRN annotation data for PyMOL visualization.

This script:
1. Loads GRN-annotated structures
2. Exports GRN labels as PyMOL selection scripts
3. Creates color-by-GRN schemes
4. Generates water network connection data

Output files:
- grn_selections.pml: PyMOL selection definitions for GRN positions
- grn_colors.pml: Color scheme for binding pocket residues
- water_networks.pml: Distance measurements for water networks
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Set

import pandas as pd

import protos
from protos.processing.structure import StructureProcessor

DATA_ROOT = Path(__file__).resolve().parents[1] / "data"
OUTPUT_DIR = DATA_ROOT / "visualizations"

# Structure metadata (same as visualization script)
STRUCTURES: Dict[str, Dict[str, Any]] = {
    "2RH1": {"chain": "A", "ligand_type": "inverse_agonist", "state": "inactive"},
    "3NY9": {"chain": "A", "ligand_type": "inverse_agonist", "state": "inactive"},
    "3SN6": {"chain": "R", "ligand_type": "full_agonist", "state": "active"},
    "4LDO": {"chain": "A", "ligand_type": "full_agonist", "state": "active"},
    "2VT4": {"chain": "A", "ligand_type": "antagonist", "state": "inactive"},
    "2Y03": {"chain": "A", "ligand_type": "full_agonist", "state": "active_like"},
    "2Y04": {"chain": "A", "ligand_type": "partial_agonist", "state": "intermediate"},
    "2Y00": {"chain": "A", "ligand_type": "partial_agonist", "state": "intermediate"},
}

# Key binding pocket GRN positions
BINDING_POCKET_GRNS = [
    "3.28", "3.29", "3.32", "3.33", "3.36", "3.37",
    "5.39", "5.40", "5.43", "5.44", "5.46",
    "6.48", "6.51", "6.52", "6.55",
    "7.35", "7.38", "7.39", "7.42",
]

# GRN color scheme (by TM helix)
GRN_COLORS = {
    "1": "red",
    "2": "orange",
    "3": "yellow",
    "4": "lime",
    "5": "cyan",
    "6": "blue",
    "7": "purple",
    "8": "pink",
    "12": "salmon",  # ICL1
    "23": "olive",   # ECL1
    "34": "teal",    # ICL2
    "45": "violet",  # ECL2
}


def get_grn_color(grn: str) -> str:
    """Get PyMOL color name for a GRN position."""
    tm = grn.split(".")[0]
    return GRN_COLORS.get(tm, "gray")


def generate_grn_selections(sp: StructureProcessor, output_path: Path):
    """Generate PyMOL selection definitions for GRN positions."""
    lines = [
        "# GRN Position Selections",
        "# Generated by prepare_pymol_grn_labels.py",
        "",
    ]

    # Collect all GRN residues across structures
    grn_residues: Dict[str, Dict[str, List[str]]] = {}  # grn -> {pdb_id -> [resi]}

    for pdb_id, meta in STRUCTURES.items():
        chain = meta["chain"]

        # Try to load GRN annotations
        try:
            df = sp.load_entity(pdb_id)
            if "grn" not in df.columns:
                # Annotate if not already done
                sp.annotate_with_grn(pdb_id, chains=[chain])
                df = sp.load_entity(pdb_id)

            if "grn" not in df.columns:
                print(f"  {pdb_id}: No GRN annotations available")
                continue

            # Get GRN-annotated residues
            grn_df = df[df["grn"].notna()][["auth_seq_id", "grn"]].drop_duplicates()

            for _, row in grn_df.iterrows():
                grn = row["grn"]
                resi = str(row["auth_seq_id"])

                if grn not in grn_residues:
                    grn_residues[grn] = {}
                if pdb_id not in grn_residues[grn]:
                    grn_residues[grn][pdb_id] = []
                grn_residues[grn][pdb_id].append(resi)

            print(f"  {pdb_id}: {len(grn_df)} GRN positions")

        except Exception as e:
            print(f"  {pdb_id}: Error loading GRN annotations: {e}")

    # Generate selections for binding pocket positions
    lines.append("# Binding pocket GRN selections")
    lines.append("")

    for grn in sorted(BINDING_POCKET_GRNS):
        if grn not in grn_residues:
            continue

        grn_safe = grn.replace(".", "_")
        sel_parts = []

        for pdb_id, resi_list in grn_residues[grn].items():
            obj_name = f"{pdb_id}_gpcr"
            chain = STRUCTURES[pdb_id]["chain"]
            resi_str = "+".join(resi_list)
            sel_parts.append(f"({obj_name} and chain {chain} and resi {resi_str})")

        if sel_parts:
            selection = " or ".join(sel_parts)
            lines.append(f"select grn_{grn_safe}, {selection}")

    # Generate selection for all binding pocket residues
    lines.append("")
    lines.append("# Combined binding pocket selection")
    bp_sels = [f"grn_{grn.replace('.', '_')}" for grn in BINDING_POCKET_GRNS if grn in grn_residues]
    if bp_sels:
        lines.append(f"select binding_pocket, {' or '.join(bp_sels)}")

    # Generate per-structure binding residue selections
    lines.append("")
    lines.append("# Per-structure binding pocket selections")

    for pdb_id in STRUCTURES.keys():
        obj_name = f"{pdb_id}_gpcr"
        grn_sels = []
        for grn in BINDING_POCKET_GRNS:
            if grn in grn_residues and pdb_id in grn_residues[grn]:
                grn_safe = grn.replace(".", "_")
                grn_sels.append(f"grn_{grn_safe}")
        if grn_sels:
            lines.append(f"select {pdb_id}_binding, ({obj_name}) and ({' or '.join(grn_sels)})")

    # Write file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    print(f"  Saved: {output_path}")
    return grn_residues


def generate_grn_colors(grn_residues: Dict, output_path: Path):
    """Generate PyMOL color commands for GRN positions."""
    lines = [
        "# GRN Position Colors",
        "# Colored by TM helix",
        "",
        "# Show binding pocket as sticks",
        "show sticks, binding_pocket",
        "set stick_radius, 0.2, binding_pocket",
        "",
    ]

    for grn in sorted(BINDING_POCKET_GRNS):
        if grn not in grn_residues:
            continue

        grn_safe = grn.replace(".", "_")
        color = get_grn_color(grn)
        lines.append(f"color {color}, grn_{grn_safe}")

    # Add label commands
    lines.append("")
    lines.append("# GRN Labels (run this to add labels)")
    lines.append("# Note: Labels will be at CA positions")

    for grn in sorted(BINDING_POCKET_GRNS):
        if grn not in grn_residues:
            continue

        grn_safe = grn.replace(".", "_")
        lines.append(f"label grn_{grn_safe} and name CA, \"{grn}\"")

    lines.append("")
    lines.append("# Label formatting")
    lines.append("set label_size, 14")
    lines.append("set label_color, black")
    lines.append("set label_font_id, 7")

    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    print(f"  Saved: {output_path}")


def generate_water_network_script(sp: StructureProcessor, output_path: Path):
    """Generate PyMOL script for water network visualization."""
    lines = [
        "# Water Network Visualization",
        "# Shows water-mediated contacts between residues",
        "",
        "# Water display settings",
        "set sphere_scale, 0.25, resn HOH",
        "color cyan, resn HOH",
        "",
        "# Hydrogen bond display settings",
        "set dash_color, cyan",
        "set dash_width, 2",
        "set dash_gap, 0.2",
        "",
    ]

    # Compute water networks and generate distance measurements
    pdb_ids = list(STRUCTURES.keys())

    try:
        water_network_output = sp.compute_water_networks(pdb_ids)
        water_network_results = water_network_output.get("structures", {})

        for pdb_id in pdb_ids:
            if pdb_id not in water_network_results:
                continue

            networks = water_network_results[pdb_id].get("networks", [])
            obj_name = f"{pdb_id}_gpcr"
            chain = STRUCTURES[pdb_id]["chain"]

            lines.append(f"# {pdb_id} water networks ({len(networks)} networks)")

            # Generate distance objects for bridging water contacts
            dist_count = 0
            for net_idx, network in enumerate(networks[:5]):  # Limit to first 5 networks
                bridging = network.get("bridging_waters", [])
                res_water_edges = network.get("residue_water_edges", [])

                for edge in res_water_edges[:10]:  # Limit edges
                    if not edge.get("hydrogen_bond"):
                        continue

                    res_key = edge.get("residue_key", "")
                    water_key = edge.get("water_key", "")

                    if not res_key or not water_key:
                        continue

                    # Parse residue info
                    res_parts = res_key.split(":")
                    water_parts = water_key.split(":")

                    if len(res_parts) == 2 and len(water_parts) == 2:
                        res_chain, res_id = res_parts[0], res_parts[1][3:]  # e.g., "A:GLU1005" -> "A", "1005"
                        water_chain, water_id = water_parts[0], water_parts[1][3:]

                        dist_name = f"{pdb_id}_hb_{dist_count}"
                        sel1 = f"({obj_name} and chain {res_chain} and resi {res_id} and name CA)"
                        sel2 = f"({obj_name} and chain {water_chain} and resn HOH and resi {water_id})"

                        lines.append(f"distance {dist_name}, {sel1}, {sel2}")
                        dist_count += 1

            lines.append("")

    except Exception as e:
        print(f"  Warning: Could not compute water networks: {e}")
        lines.append("# Water network computation failed")
        lines.append("# Run the workflow first to generate network data")

    lines.append("")
    lines.append("# Hide distance labels (optional)")
    lines.append("hide labels")
    lines.append("")
    lines.append("# Group all distances")
    lines.append("group water_hbonds, *_hb_*")

    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    print(f"  Saved: {output_path}")


def generate_state_comparison_script(output_path: Path):
    """Generate PyMOL script for active vs inactive comparison."""
    lines = [
        "# Active vs Inactive State Comparison",
        "",
        "# Color scheme: green=active, blue=inactive",
        "",
        "# Active state structures",
    ]

    for pdb_id, meta in STRUCTURES.items():
        obj_name = f"{pdb_id}_gpcr"
        state = meta["state"]

        if state in ["active", "active_like"]:
            lines.append(f"color green, {obj_name} and polymer.protein")
        else:
            lines.append(f"color blue, {obj_name} and polymer.protein")

    lines.extend([
        "",
        "# TM6 highlighting (activation marker)",
        "# TM6 moves outward ~14A during activation",
        "",
    ])

    for pdb_id, meta in STRUCTURES.items():
        obj_name = f"{pdb_id}_gpcr"
        chain = meta["chain"]
        state = meta["state"]

        # TM6 approximate residue range (varies by structure)
        if state in ["active", "active_like"]:
            lines.append(f"color red, {obj_name} and chain {chain} and resi 265-295")
        else:
            lines.append(f"color cyan, {obj_name} and chain {chain} and resi 265-295")

    lines.extend([
        "",
        "# View commands",
        "cmd.view('binding_pocket', 'recall')",
        "set cartoon_transparency, 0.6",
    ])

    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    print(f"  Saved: {output_path}")


def generate_master_script(output_path: Path):
    """Generate master PyMOL script that sources all other scripts."""
    lines = [
        "# GPCR Binding Pocket Comparison - Master Script",
        "# Run this after loading structures with pymol_gpcr_visualization.py",
        "",
        "# Load GRN selections",
        f"@{OUTPUT_DIR / 'grn_selections.pml'}",
        "",
        "# Apply GRN colors",
        f"@{OUTPUT_DIR / 'grn_colors.pml'}",
        "",
        "# State comparison coloring (optional)",
        f"# @{OUTPUT_DIR / 'state_comparison.pml'}",
        "",
        "# Water network visualization (optional)",
        f"# @{OUTPUT_DIR / 'water_networks.pml'}",
        "",
        "# Final view setup",
        "deselect",
        "center binding_pocket",
        "zoom binding_pocket, buffer=5",
        "",
        "print('GPCR visualization setup complete!')",
        "print('Use these commands to explore:')",
        "print('  show_only_active()     - Show active states')",
        "print('  show_only_inactive()   - Show inactive states')",
        "print('  show_water_comparison() - Highlight waters')",
    ]

    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    print(f"  Saved: {output_path}")


def main():
    """Generate all PyMOL annotation scripts."""
    print("=" * 60)
    print("Preparing PyMOL GRN Annotations")
    print("=" * 60)

    protos.set_data_path(str(DATA_ROOT))
    sp = StructureProcessor()

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    print("\n[1/5] Generating GRN selections...")
    grn_residues = generate_grn_selections(sp, OUTPUT_DIR / "grn_selections.pml")

    print("\n[2/5] Generating GRN colors...")
    generate_grn_colors(grn_residues, OUTPUT_DIR / "grn_colors.pml")

    print("\n[3/5] Generating water network script...")
    generate_water_network_script(sp, OUTPUT_DIR / "water_networks.pml")

    print("\n[4/5] Generating state comparison script...")
    generate_state_comparison_script(OUTPUT_DIR / "state_comparison.pml")

    print("\n[5/5] Generating master script...")
    generate_master_script(OUTPUT_DIR / "gpcr_master.pml")

    print("\n" + "=" * 60)
    print("ANNOTATION SCRIPTS GENERATED")
    print("=" * 60)
    print(f"\nOutput directory: {OUTPUT_DIR}")
    print("\nTo use in PyMOL:")
    print("  1. Run: pymol scripts/pymol_gpcr_visualization.py")
    print("  2. Then: @data/visualizations/gpcr_master.pml")
    print("\nOr run individual scripts:")
    print("  @data/visualizations/grn_selections.pml")
    print("  @data/visualizations/grn_colors.pml")


if __name__ == "__main__":
    main()
